### ISSUE TITLE
TCP scan, not SYN scan

### ISSUE THREAD

**Issue by slavkoja** [pdrb/synping#1]
Because it performs full TCP handshake, it is not SYN scan, but regular TCP scan, and thus your description & name is misleading.

**Comment by pdrb** [comment]
I got your point.

This is a simple tool to check latency and not intendend to use as a scan tool.

The name was chosen because syn packets are used (during the tcp handshake) to measure the latency. We actually want to do the full handshake and to explict close the connection after each "ping" to behave nicely.

I will update the readme to avoid futher confusion.

Thanks for the feedback.
